# Generated by Django 6.0.6 on 2026-06-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly stipend in USD. Leave blank if unpaid.', max_digits=10, null=True)),
                ('skills_required', models.TextField(blank=True, default='', help_text='Comma-separated list of required skills.')),
                ('duration_weeks', models.PositiveSmallIntegerField(help_text='Expected duration of the internship in weeks.')),
                ('application_deadline', models.DateField(blank=True, help_text='Last date to apply. Null means no deadline.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'internships',
                'ordering': ['-created_at'],
            },
        ),
    ]
