# Generated by Django 6.0.6 on 2026-06-04 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='user',
            field=models.ForeignKey(help_text='The company account that owns this posting.', on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['status', '-created_at'], name='idx_internship_status_date'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['user', 'status'], name='idx_internship_user_status'),
        ),
    ]
