# Generated by Django 6.0.6 on 2026-06-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='idx_app_internship_status',
            old_name='idx_application_internship_status',
        ),
    ]
